"""

Revision ID: 033e52d43c5e
Revises: 8d3dadfa6ffe
Create Date: 2026-04-17 16:55:58.483356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033e52d43c5e'
down_revision: Union[str, Sequence[str], None] = '8d3dadfa6ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whores', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whores', 'update_time')
    # ### end Alembic commands ###
