"""

Revision ID: 84faed40981d
Revises: 
Create Date: 2026-04-21 16:25:35.492455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84faed40981d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characteristics',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('clients',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('referral', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('pimps',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('whores',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('pimp_uid', sa.UUID(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pimp_uid'], ['pimps.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('characteristics_whore',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('whore_uid', sa.UUID(), nullable=False),
    sa.Column('characteristic_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_uid'], ['characteristics.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whore_uid'], ['whores.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('clients_whore',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('client_uid', sa.UUID(), nullable=False),
    sa.Column('whore_uid', sa.UUID(), nullable=False),
    sa.Column('date_of_visit', sa.DateTime(), nullable=False),
    sa.Column('cost_of_visit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_uid'], ['clients.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whore_uid'], ['whores.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients_whore')
    op.drop_table('characteristics_whore')
    op.drop_table('whores')
    op.drop_table('pimps')
    op.drop_table('clients')
    op.drop_table('characteristics')
    # ### end Alembic commands ###
