"""

Revision ID: 8d3dadfa6ffe
Revises: 05ae8b55489c
Create Date: 2026-04-17 16:38:17.916106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3dadfa6ffe'
down_revision: Union[str, Sequence[str], None] = '05ae8b55489c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('characteristics_whore_whore_uid_fkey'), 'characteristics_whore', type_='foreignkey')
    op.drop_constraint(op.f('characteristics_whore_characteristic_uid_fkey'), 'characteristics_whore', type_='foreignkey')
    op.create_foreign_key(None, 'characteristics_whore', 'whores', ['whore_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'characteristics_whore', 'characteristics', ['characteristic_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint(op.f('clients_whore_whore_uid_fkey'), 'clients_whore', type_='foreignkey')
    op.drop_constraint(op.f('clients_whore_client_uid_fkey'), 'clients_whore', type_='foreignkey')
    op.create_foreign_key(None, 'clients_whore', 'clients', ['client_uid'], ['uid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clients_whore', 'whores', ['whore_uid'], ['uid'], ondelete='CASCADE')
    op.drop_constraint(op.f('whores_pimp_uid_fkey'), 'whores', type_='foreignkey')
    op.create_foreign_key(None, 'whores', 'pimps', ['pimp_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whores', type_='foreignkey')
    op.create_foreign_key(op.f('whores_pimp_uid_fkey'), 'whores', 'pimps', ['pimp_uid'], ['uid'])
    op.drop_constraint(None, 'clients_whore', type_='foreignkey')
    op.drop_constraint(None, 'clients_whore', type_='foreignkey')
    op.create_foreign_key(op.f('clients_whore_client_uid_fkey'), 'clients_whore', 'clients', ['client_uid'], ['uid'])
    op.create_foreign_key(op.f('clients_whore_whore_uid_fkey'), 'clients_whore', 'whores', ['whore_uid'], ['uid'])
    op.drop_constraint(None, 'characteristics_whore', type_='foreignkey')
    op.drop_constraint(None, 'characteristics_whore', type_='foreignkey')
    op.create_foreign_key(op.f('characteristics_whore_characteristic_uid_fkey'), 'characteristics_whore', 'characteristics', ['characteristic_uid'], ['uid'])
    op.create_foreign_key(op.f('characteristics_whore_whore_uid_fkey'), 'characteristics_whore', 'whores', ['whore_uid'], ['uid'])
    # ### end Alembic commands ###
